### ISSUE TITLE
`go build -o ./v2gen'  failed

### ISSUE THREAD

**Issue by hongyi-zhao** [iochen/v2gen#1]
Hi, 

See the following:

$ git clone https://github.com/iochen/V2Gen.git V2Gen.git 
$ cd  V2Gen.git 
$ go build -o ./v2gen
go: cannot find main module, but found .git/config in /home/werner/software/anti-gfw/socks5/v2ray/V2Gen.git
	to create a module there, run:
	go mod init
$

Any hints?

**Comment by rikkihamano** [comment]
Thanks for your feedback.
It is fixed now.
Please try again.
