### ISSUE TITLE
Can't run the program

### ISSUE THREAD

**Issue by Tim-Paik** [iochen/v2gen#17]
**Describe the bug**
Can't run the program

**To Reproduce**
Download the latest version release and run it
```
./v2gen_amd64_linux: line 1: syntax error near unexpected token `newline'
./v2gen_amd64_linux: line 1: `!<arch>'
```

**Desktop (please complete the following information):**
 - OS: Windows10 LTSC and Archlinux latest
 - Version 1.4.2

I found that the executable file size is only about 10kb, which is not normal for a golang application
The release and compiled versions of V1.4.2 also have problems
V1.4.1 looks normal?

**Comment by rikkihamano** [comment]
The reason has been found.
https://github.com/iochen/v2gen/blob/db7e9dc85bd3753a5cbbaa11f0937612452198a1/cmd/v2gen/main.go#L1
This should be `main`, but I made a mistake.

Will be fixed in `V1.4.2.1`

**Comment by rikkihamano** [comment]
Available now.

https://github.com/iochen/v2gen/releases/tag/V1.4.2.1

**Comment by Tim-Paik** [comment]
Thanks, it really helped me a lot
