### ISSUE TITLE
Runing `v2gen -u "https://api.xinjie.eu.org/link/89j4g4oET" -o "-"` leads to error

### ISSUE THREAD

**Issue by tinybright** [iochen/v2gen#20]
**Describe the bug**

**To Reproduce**
run `v2gen -u "https://api.xinjie.eu.org/link/89j4g4oET" -o "-"`

**Expected behavior**
show list

**Desktop (please complete the following information):**
 - OS: centos

**Additional context**
`2020/08/17 11:32:59 v2ray.com/core/infra/conf: failed to parse to outbound detour config. > invalid character '<' looking for beginning of value
2020/08/17 11:32:59 v2ray.com/core/infra/conf: failed to parse to outbound detour config. > invalid character '<' looking for beginning of value
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x794d62]

goroutine 11 [running]:
v2ray.com/core.(*Instance).Start(0x0, 0x0, 0x0)
	/home/runner/work/v2gen/v2gen/go/src/v2ray.com/core/v2ray.go:311 +0x42
iochen.com/v2gen/app/ping/vmessping.VmessPing(0xc00005c728, 0x3, 0xd06f21, 0x24, 0x19, 0x8, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/v2gen/v2gen/go/src/iochen.com/v2gen/app/ping/vmessping/vmessping.go:17 +0xe1
iochen.com/v2gen.Ping(0xc00005c728, 0x0, 0x0, 0x0)
	/home/runner/work/v2gen/v2gen/go/src/iochen.com/v2gen/ping.go:106 +0x139
iochen.com/v2gen.MakeNode(0x0, 0xc000437600, 0x17, 0xc000437560, 0x11, 0xb97920, 0xc0000364d8, 0xc00003a510, 0x24, 0x0, ...)
	/home/runner/work/v2gen/v2gen/go/src/iochen.com/v2gen/ping.go:87 +0x2f
created by iochen.com/v2gen.PingNodes.func1
	/home/runner/work/v2gen/v2gen/go/src/iochen.com/v2gen/ping.go:55 +0x152
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x794d62]

goroutine 12 [running]:
v2ray.com/core.(*Instance).Start(0x0, 0x0, 0x0)
	/home/runner/work/v2gen/v2gen/go/src/v2ray.com/core/v2ray.go:311 +0x42
iochen.com/v2gen/app/ping/vmessping.VmessPing(0xc00005cf28, 0x3, 0xd06f21, 0x24, 0x19, 0x8, 0x0, 0x0, 0x0, 0x0)
	/home/runner/work/v2gen/v2gen/go/src/iochen.com/v2gen/app/ping/vmessping/vmessping.go:17 +0xe1
iochen.com/v2gen.Ping(0xc00005cf28, 0x0, 0x0, 0x0)
	/home/runner/work/v2gen/v2gen/go/src/iochen.com/v2gen/ping.go:106 +0x139
iochen.com/v2gen.MakeNode(0x1, 0xc000437680, 0x19, 0xc000437640, 0x11, 0xb97920, 0xc0000364f8, 0xc00003a540, 0x24, 0x0, ...)
	/home/runner/work/v2gen/v2gen/go/src/iochen.com/v2gen/ping.go:87 +0x2f
created by iochen.com/v2gen.PingNodes.func1
	/home/runner/work/v2gen/v2gen/go/src/iochen.com/v2gen/ping.go:55 +0x152
`

**Comment by rikkihamano** [comment]
please wait for `v2.0.0`, which would be easier for me to trace the problem.
`v2.0.0` would be released on about next sunday.

**Comment by rikkihamano** [comment]
please use v2.0.0 in release and run
```
v2gen -u "https://xxxx/xxxxx" -o "-" -loglevel trace -log v2gen.log
```
then, please upload `v2gen.log` file, which is safe to upload, for further investigation.

**Comment by tinybright** [comment]
[REDACTED]

```
[root@devserver ~]# v2gen -u "[REDACTED]" -o "-" -loglevel trace -log v2gen.log
v2gen v2.0.0, V2Ray 4.27.0 (go1.14.7 8cores linux/amd64)
Pinging 35/35
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbb2d93]

goroutine 1 [running]:
main.main()
	/home/runner/work/v2gen/v2gen/cmd/v2gen/main.go:255 +0xdd3
```

**Comment by rikkihamano** [comment]
Fixed! 
Release is avaliable [here](https://github.com/iochen/v2gen/releases/tag/v2.0.0.1).

---

Your subscribe link may be leaked, although I have helped you redact them, please reset your subscribe link ASAP.
I'm so sorry for that, this security issue will be fix in next version.
