### ISSUE TITLE
输出端口更改无效

### ISSUE THREAD

**Issue by w934423231** [iochen/v2gen#23]
我设置了v2gen的v2gen.ini里的httpPort，但是我再次生成v2配置文件时，他的输出端口还是1080

**Comment by rikkihamano** [comment]
默认 `1080` 的是 `socksPort` 不是 `httpPort`
你可能改错了

https://github.com/iochen/v2gen#v2gen-user-config

**Comment by rikkihamano** [comment]
fixed in lastest release: https://github.com/iochen/v2gen/releases/tag/v2.0.1
