### ISSUE TITLE
./v2gen_amd64_linux --init or ./v2gen_amd64_linux -init 报错

### ISSUE THREAD

**Issue by RiotGamesU** [iochen/v2gen#25]
```
root@VM-0-7-debian:~/v2ray# ./v2gen_amd64_linux --init
v2gen v2.0.1, V2Ray 4.31.0 (go1.15.8 1cores linux/amd64)
panic: open /etc/v2ray/v2gen.ini: no such file or directory

goroutine 1 [running]:
main.main()
	/home/runner/work/v2gen/v2gen/cmd/v2gen/main.go:163 +0x20a5
root@VM-0-7-debian:~/v2ray# ./v2gen_amd64_linux -init
v2gen v2.0.1, V2Ray 4.31.0 (go1.15.8 1cores linux/amd64)
panic: open /etc/v2ray/v2gen.ini: no such file or directory

goroutine 1 [running]:
main.main()
	/home/runner/work/v2gen/v2gen/cmd/v2gen/main.go:163 +0x20a5

```

**Comment by RiotGamesU** [comment]
补充:
1.系统环境:
```
root@VM-0-7-debian:~/v2ray# uname -a
Linux VM-0-7-debian 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux
root@VM-0-7-debian:~/v2ray# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
2.没有go

**Comment by rikkihamano** [comment]
> panic: open /etc/v2ray/v2gen.ini: no such file or directory

先运行：
`sudo mkdir /etc/v2ray/`

**Comment by RiotGamesU** [comment]
> > panic: open /etc/v2ray/v2gen.ini: no such file or directory
> 
> 先运行：
> `sudo mkdir /etc/v2ray/`

请问你指的是安装v2ray吗,我已经通过安装脚本安装了最新版的v2ray,然后系统里也不存在这个目录,我的v2ray配置文件在/usr/local/etc/v2ray/config.json

**Comment by rikkihamano** [comment]
> > > panic: open /etc/v2ray/v2gen.ini: no such file or directory
> > 
> > 
> > 先运行：
> > `sudo mkdir /etc/v2ray/`
> 
> 请问你指的是安装v2ray吗,我已经通过安装脚本安装了最新版的v2ray,然后系统里也不存在这个目录,我的v2ray配置文件在/usr/local/etc/v2ray/config.json

因为该工具编写时，V2Ray 配置文件还都是在 `/etc/v2ray/` 文件夹中，遂默认路径也均在 `/etc/v2ray/` 文件夹中。
由于本人不再使用该工具，因而未作出更改。
你可以通过 `-config` 指定 **v2gen** 的配置路径，
通过 `-o` 指定生成的 **V2Ray** 配置的路径。

**Comment by RiotGamesU** [comment]
> > > > panic: open /etc/v2ray/v2gen.ini: no such file or directory
> > > 
> > > 
> > > 先运行：
> > > `sudo mkdir /etc/v2ray/`
> > 
> > 
> > 请问你指的是安装v2ray吗,我已经通过安装脚本安装了最新版的v2ray,然后系统里也不存在这个目录,我的v2ray配置文件在/usr/local/etc/v2ray/config.json
> 
> 因为该工具编写时，V2Ray 配置文件还都是在 `/etc/v2ray/` 文件夹中，遂默认路径也均在 `/etc/v2ray/` 文件夹中。
> 由于本人不再使用该工具，因而未作出更改。
> 你可以通过 `-config` 指定 **v2gen** 的配置路径，
> 通过 `-o` 指定生成的 **V2Ray** 配置的路径。

好的谢谢

**Comment by RiotGamesU** [comment]
> > > > > panic: open /etc/v2ray/v2gen.ini: no such file or directory
> > > > 
> > > > 
> > > > 先运行：
> > > > `sudo mkdir /etc/v2ray/`
> > > 
> > > 
> > > 请问你指的是安装v2ray吗,我已经通过安装脚本安装了最新版的v2ray,然后系统里也不存在这个目录,我的v2ray配置文件在/usr/local/etc/v2ray/config.json
> > 
> > 
> > 因为该工具编写时，V2Ray 配置文件还都是在 `/etc/v2ray/` 文件夹中，遂默认路径也均在 `/etc/v2ray/` 文件夹中。
> > 由于本人不再使用该工具，因而未作出更改。
> > 你可以通过 `-config` 指定 **v2gen** 的配置路径，
> > 通过 `-o` 指定生成的 **V2Ray** 配置的路径。
> 
> 好的谢谢



> > > > panic: open /etc/v2ray/v2gen.ini: no such file or directory
> > > 
> > > 
> > > 先运行：
> > > `sudo mkdir /etc/v2ray/`
> > 
> > 
> > 请问你指的是安装v2ray吗,我已经通过安装脚本安装了最新版的v2ray,然后系统里也不存在这个目录,我的v2ray配置文件在/usr/local/etc/v2ray/config.json
> 
> 因为该工具编写时，V2Ray 配置文件还都是在 `/etc/v2ray/` 文件夹中，遂默认路径也均在 `/etc/v2ray/` 文件夹中。
> 由于本人不再使用该工具，因而未作出更改。
> 你可以通过 `-config` 指定 **v2gen** 的配置路径，
> 通过 `-o` 指定生成的 **V2Ray** 配置的路径。

请问有类似的工具推荐一下吗,订阅链接生成配置文件这样的工具

**Comment by rikkihamano** [comment]
> > > > > > panic: open /etc/v2ray/v2gen.ini: no such file or directory
> > > > > 
> > > > > 
> > > > > 先运行：
> > > > > `sudo mkdir /etc/v2ray/`
> > > > 
> > > > 
> > > > 请问你指的是安装v2ray吗,我已经通过安装脚本安装了最新版的v2ray,然后系统里也不存在这个目录,我的v2ray配置文件在/usr/local/etc/v2ray/config.json
> > > 
> > > 
> > > 因为该工具编写时，V2Ray 配置文件还都是在 `/etc/v2ray/` 文件夹中，遂默认路径也均在 `/etc/v2ray/` 文件夹中。
> > > 由于本人不再使用该工具，因而未作出更改。
> > > 你可以通过 `-config` 指定 **v2gen** 的配置路径，
> > > 通过 `-o` 指定生成的 **V2Ray** 配置的路径。
> > 
> > 
> > 好的谢谢
> 
> > > > > panic: open /etc/v2ray/v2gen.ini: no such file or directory
> > > > 
> > > > 
> > > > 先运行：
> > > > `sudo mkdir /etc/v2ray/`
> > > 
> > > 
> > > 请问你指的是安装v2ray吗,我已经通过安装脚本安装了最新版的v2ray,然后系统里也不存在这个目录,我的v2ray配置文件在/usr/local/etc/v2ray/config.json
> > 
> > 
> > 因为该工具编写时，V2Ray 配置文件还都是在 `/etc/v2ray/` 文件夹中，遂默认路径也均在 `/etc/v2ray/` 文件夹中。
> > 由于本人不再使用该工具，因而未作出更改。
> > 你可以通过 `-config` 指定 **v2gen** 的配置路径，
> > 通过 `-o` 指定生成的 **V2Ray** 配置的路径。
> 
> 请问有类似的工具推荐一下吗,订阅链接生成配置文件这样的工具

https://github.com/search?q=V2Ray+%E8%AE%A2%E9%98%85

**Comment by RiotGamesU** [comment]
> > > > > > > panic: open /etc/v2ray/v2gen.ini: no such file or directory
> > > > > > 
> > > > > > 
> > > > > > 先运行：
> > > > > > `sudo mkdir /etc/v2ray/`
> > > > > 
> > > > > 
> > > > > 请问你指的是安装v2ray吗,我已经通过安装脚本安装了最新版的v2ray,然后系统里也不存在这个目录,我的v2ray配置文件在/usr/local/etc/v2ray/config.json
> > > > 
> > > > 
> > > > 因为该工具编写时，V2Ray 配置文件还都是在 `/etc/v2ray/` 文件夹中，遂默认路径也均在 `/etc/v2ray/` 文件夹中。
> > > > 由于本人不再使用该工具，因而未作出更改。
> > > > 你可以通过 `-config` 指定 **v2gen** 的配置路径，
> > > > 通过 `-o` 指定生成的 **V2Ray** 配置的路径。
> > > 
> > > 
> > > 好的谢谢
> > 
> > 
> > > > > > panic: open /etc/v2ray/v2gen.ini: no such file or directory
> > > > > 
> > > > > 
> > > > > 先运行：
> > > > > `sudo mkdir /etc/v2ray/`
> > > > 
> > > > 
> > > > 请问你指的是安装v2ray吗,我已经通过安装脚本安装了最新版的v2ray,然后系统里也不存在这个目录,我的v2ray配置文件在/usr/local/etc/v2ray/config.json
> > > 
> > > 
> > > 因为该工具编写时，V2Ray 配置文件还都是在 `/etc/v2ray/` 文件夹中，遂默认路径也均在 `/etc/v2ray/` 文件夹中。
> > > 由于本人不再使用该工具，因而未作出更改。
> > > 你可以通过 `-config` 指定 **v2gen** 的配置路径，
> > > 通过 `-o` 指定生成的 **V2Ray** 配置的路径。
> > 
> > 
> > 请问有类似的工具推荐一下吗,订阅链接生成配置文件这样的工具
> 
> https://github.com/search?q=V2Ray+%E8%AE%A2%E9%98%85

thx
