### ISSUE TITLE
v2gen --init  still will fail.

### ISSUE THREAD

**Issue by hongyi-zhao** [iochen/v2gen#3]
See the following:

$ ./v2gen --init
panic: open /etc/v2ray/v2gen.ini: no such file or directory

goroutine 1 [running]:
main.checkErr(...)
	/home/werner/software/anti-gfw/socks5/v2ray/V2Gen.git/main.go:64
main.main()
	/home/werner/software/anti-gfw/socks5/v2ray/V2Gen.git/main.go:45 +0x1ef

**Comment by iochen** [comment]
Because it will write to /etc/v2ray/v2gen.ini , so you should use

sudo ./v2gen --init

**Comment by iochen** [comment]
or use `-c xxx/xxx/v2gen.ini` to save to a custom path
and add `-c xxx/xxx/v2gen.ini` when you generate a V2Ray config

**Comment by rikkihamano** [comment]
Try `sudo ./v2gen --init`
As it will write to `/etc/v2ray/v2gen.ini` by default

**Comment by rikkihamano** [comment]
or try `-c xxx/xxx/v2gen.ini` to save to a custom path
and add `-c xxx/xxx/v2gen.ini` when you generate a V2Ray config

**Comment by rikkihamano** [comment]
It seems that you do not have `/etc/v2ray/` folder,
try `sudo mkdir /etc/v2ray/` first or try https://github.com/iochen/V2Gen/issues/3#issuecomment-531257320

**Comment by hongyi-zhao** [comment]
I use the v2ray directly instead of installing it, so I don't have that folder.

**Comment by rikkihamano** [comment]
you can make that folder or use another path like the solutions above.

**Comment by hongyi-zhao** [comment]
Thanks, got it.
