### ISSUE TITLE
使用谷歌访问速度替代ICMP速度

### ISSUE THREAD

**Issue by cxgreat2014** [iochen/v2gen#8]
目前不少服务商推出了云中转服务，使用ICMP进行测试变得没有太多实际意义，建议使用以下函数替代ping函数。

https://github.com/ld000/freess-crawler/blob/master/test_methods/ping.go#L47:6

**Comment by rikkihamano** [comment]
This feature will be added in recent few versions.

**Comment by rikkihamano** [comment]
I'll use v2fly/vmessping lib, instead of ld000/freess-crawler, cause it should test speed or ping after connecting to the node.

**Comment by cxgreat2014** [comment]
👍

**Comment by rikkihamano** [comment]
It uses vmess ping by default now.

**Comment by cxgreat2014** [comment]
do you have any plan to sort nodes by vmess ping and add fetures to command line to automatic select best one to generate v2ray config?

**Comment by rikkihamano** [comment]
> do you have any plan to sort nodes by vmess ping and add fetures to command line to automatic select best one to generate v2ray config?

Yes, but please reopen an issue so that I can add it to the milestone. Thank you for your suggestions.
